### PR TITLE
general changes and improvements

### PR DESCRIPTION
**Pull request by superbigio**
1) `ltc_frame_get_user_bits()`:
used binary OR operator instead of arithmetic + operator.
Faster to compute and more appropriate for bit manipulations.

2) deprecated `parse_bcg_flags()` and renamed it `ltc_frame_parse_bcg_flags()`
What does 'bcg' stand for BTW?

3) deprecated `ltc_encoder_get_bufptr()` and renamed it `ltc_encoder_get_bufferptr()`
Reason for deprecation was a change in argument order that is more consistent with other functions such as `ltc_encoder_get_buffer()`, `ltc_encoder_copy_buffer()`, etc...
So we set the buffer pointer by passing it as an argument by reference and we return the size/number of bytes.
In the future you may want to set the size by reference as well and use the return value for a status/error indicator, as you are already doing in some other functions.

4) fixed some comments that were referencing deprecated functions

Both deprecated functions are exported and turned them into wrappers for the new functions as I did previously. Nothing should break.

Your library works really well. I have just finished writing an encoder Max/MSP external, that allows you to change FPS, sample rate and volume on-the-fly in real time. I am gonna start writing the decoder part now.

### CODE REVIEW

**Comment by x42** [comment]
> What does 'bcg' stand for BTW?

It's an abbreviation used in the LTC spec for "binary coded group flags"

> used binary OR operator instead of arithmetic + operator.

There were some issues with packed data-types and bitwise operators. If I remember correctly on ARM. I'll have to verify that and/or look through some old notes.

If you don't mind I'll only merge the other 5 commits only, and postpone this for the time being.

> I have just finished writing an encoder Max/MSP external, that allows you to change FPS, sample rate and volume on-the-fly in real time.

Wow this is really cool! Thanks. Can I add a link from the doc to your project when it's done?

**Comment by superbigio** [comment]
Yes, no problem of course. It's your library.
Merge only what you feel comfortable merging.

The only thing I want to make sure is that you don't merge commit:
**be398ce**
I messed up on that one.

> Can I add a link from the doc to your project when it's done?

Yes, of course I will give you a link when it's all ready to go.
Cheers.

**Comment by x42** [comment]
I've re-done your patch-queue, separated white-space changes and also updated text/example code, and wrote proper commit messages with a short summary line.

622e82a00...5debe4581  should be everything except the `|=` -> `+=` changes.

It would be great if you could double-check that this work for you. Cheers!

**Comment by superbigio** [comment]
Yes, will double-check and report back to you. Thanks!

**Comment by superbigio** [comment]
Yes, everything seems to be there.
The only thing is `ltc_frame_parse_bcg_flags()` is named `ltc_parse_bcg_flags()`
I am not sure this is intentional or just a minor oversight.
I thought `ltc_frame_parse_bcg_flags()` was more appropriate because of the first argument of the function being an LTCFrame, but I am good either way.
Thanks a lot for your support.

**Comment by x42** [comment]
It was an oversight. Thanks for the heads up. I'll fix it

**Comment by x42** [comment]
With #52 this PR should be complete now.

**Pull request closed without merging**
